replicaCount: 3

image:
  repository: 192.168.1.200:30002/ivansanmartin/roulette-backend
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "roulette-backend"
fullnameOverride: "roulette-backend"

namespace: ivansanmartin

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
  
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

securityContext:
  runAsUser: 0

labels:
  app: roulette-backend